# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: UdiBurg.BurgBackup
PackageVersion: 2.1.6
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/007me/BurgBackup/releases/download/v2.1.6/BurgBackup-2.1.6-x64.msi
  InstallerSha256: 7C0BC8BE231540BDA8675EB782611C0FCB04882D27F9C1C391035A2FF55B86A6
  UpgradeBehavior: install
  ProductCode: '{288B9617-B19E-46B5-BF7E-385E1B080149}'
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
